let x = 5;
try
{
  x = y + 1;   // y cannot be used (referenced)
}
catch
(err) {
  console.log("asu")
}

if
(x>4)
{
    console.log("asu")
}